[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.gd', 'php83Extensions.intl', 'php83Extensions.bcmath', 'php83Extensions.tokenizer', 'composer']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist'
]

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan migrate --force && php artisan db:seed --force && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=${PORT}'
